version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      MONGO_INITDB_DATABASE: rpg
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: userTst
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo1234
      ME_CONFIG_MONGODB_URL: mongodb://root:MongoDB2019!@mongo:27017/
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge